# Generated by Django 4.1 on 2023-01-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acontecimento_negativo', models.TextField(max_length=100, verbose_name='Acontecimento Negativo')),
                ('acontecimento_positivo', models.TextField(max_length=100, verbose_name='Acontecimento Positivo')),
                ('estado_mental', models.CharField(choices=[('B', 'BOM'), ('E', 'EXCELENTE'), ('R', 'RUIM'), ('P', 'PÉSSIMO')], max_length=30, verbose_name='Selecione o seu estado mental atual')),
                ('alerta_crises', models.CharField(choices=[('D', 'DEPRESSAO'), ('P', 'PANICO'), ('A', 'ANSIEDADE')], max_length=30, verbose_name='Selecione o seu estado de crise')),
                ('data_atual', models.DateTimeField(auto_now=True)),
                ('data_acontecimento', models.DateTimeField()),
                ('data_superaçao', models.DateTimeField()),
            ],
        ),
    ]
