# Generated by Django 4.1 on 2023-01-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='alerta_crises',
            field=models.CharField(choices=[('P', 'PANICO'), ('A', 'ANSIEDADE'), ('D', 'DEPRESSAO')], max_length=30, verbose_name='Selecione o seu estado de crise'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado_mental',
            field=models.CharField(choices=[('R', 'RUIM'), ('E', 'EXCELENTE'), ('B', 'BOM'), ('P', 'PÉSSIMO')], max_length=30, verbose_name='Selecione o seu estado mental atual'),
        ),
    ]
