# Generated by Django 4.1 on 2023-01-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_alter_pessoa_alerta_crises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='alerta_crises',
            field=models.CharField(choices=[('D', 'DEPRESSAO'), ('P', 'PANICO'), ('A', 'ANSIEDADE')], max_length=2, verbose_name='Selecione o seu estado de crise'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado_mental',
            field=models.CharField(choices=[('R', 'RUIM'), ('P', 'PÉSSIMO'), ('E', 'EXCELENTE'), ('B', 'BOM')], max_length=2, verbose_name='Selecione o seu estado mental atual'),
        ),
    ]
