# Generated by Django 4.1 on 2023-01-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_alter_pessoa_alerta_crises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado_mental',
            field=models.CharField(choices=[('P', 'PÉSSIMO'), ('E', 'EXCELENTE'), ('R', 'RUIM'), ('B', 'BOM')], max_length=2, verbose_name='Selecione o seu estado mental atual'),
        ),
    ]
