# Generated by Django 4.1 on 2023-01-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_pessoa_nome_alter_pessoa_estado_mental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='alerta_crises',
            field=models.CharField(choices=[('D', 'DEPRESSAO'), ('A', 'ANSIEDADE'), ('P', 'PANICO')], max_length=2, verbose_name='Selecione o seu estado de crise'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado_mental',
            field=models.CharField(choices=[('E', 'EXCELENTE'), ('P', 'PÉSSIMO'), ('B', 'BOM'), ('R', 'RUIM')], max_length=2, verbose_name='Selecione o seu estado mental atual'),
        ),
    ]
